version: '3.8'

services:
  api:
    build: .
    container_name: api
    # command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mapeia o código local para o contêiner para habilitar o hot-reload
      - .:/app
    ports:
      - "8000:8000"